incident_response_library = {
  '0':'ddos',
  '1':'probe',
  '2':'r2l',
  '3':'u2r'
}

ddos_response = '\n ==========DDOS RESPONSE========== \n \n 1.)Overprovision the Network Bandwidth: \n If the web server has more bandwidth available, you should immediately overprovision the bandwidth by around 100-500% \n (contact your ISP if you do not have the admin privileges to do this). \n \n 2.)Filter suspicious IP address packets via the network routers: \n Once the IP address source of the packets causing the DDoS attack is found, the packets sent from the source can be limited or even dropped completely. \n \n 3.) Lower UDP and ICMP Thresholds: \n By lowering these thresholds via a router, this prevents a UDP or ICMP flood attack. \n Set UDP threshold to 1000 packets/sec & ICMP threshold to 200 packets/sec. \n \n 4.) Rate limit network traffic: \n By rate limiting your router, an algorithm is activated which blocks traffic from IP addresses which have sent an unusual number of packets to the server. \n \n IF NONE OF THE STEPS SO FAR WORKED, CONTACT A DDOS MITIGATION SERVICE IMMEDIATELY. \n \n'

u2r_response = '\n ==========U2R RESPONSE========== \n \n  1.) Back Up Important Files/Data before attempting any further steps. \n \n 2.) Scan for root access malware using specialised rootkit scan tools. \n Sometimes it may be necessary to run several different scanning software’s in order to identify the root access alongside its supporting malware.\n \n 3.) Use specialised malware software to remove the rootkit malware. \n Make sure to remove all its supporting malware too to prevent the hackers accessing the target machine again. \n \n 4.) If the rootkit access is presumed not to be removed, or the hacker regains access to the target machine again, the entire target machine’s hardware will have to be wiped/hard reset. \n'

probe_response = '\n ==========PROBE RESPONSE========== \n \n 1.)Initially, when alerted of a potential probe attack the data gathered from the suspicious package should reveal the source IP address of the packets. \nOnce this data is gathered, the IP address associated with the probe should be put on a server blacklist to prevent the same IP address \nfrom then using the probe vulnerability data to attack the server. \n \n 2.)The data should then be analysed to determine what the probe attack was scanning for \n e.g Topology Mapping, Remote Operating System Identification, Port Scanning etc. \n \n 3.)Continue to investigate similar network data using OSINT software. \n \n 4.)If enough data is gathered (e.g DNS and Server registration details) and the probe source is believed to be a genuine threat, report this data to authorities. \n \n HOWEVER, IF NO FURTHER DETAILS COULD BE DISCOVERED, STAY ALERT FOR ANY ATTACKS BASED ON WHAT WAS SCANNED. \n For example, if Port Scanning occured, cross reference this with a vulnerability library to see what the attackers could utilise.'

r2l_response = '\n ==========R2L RESPONSE========== \n \n 1.)Contain The Security Breach: \n Immediately disconnect from the internet and disable any form of remote access. \n \n 2.)Install new securtiy software patches \n \n 3.)Change all important account passwords immediately. \n \n 3.)Analyse Security Logs: \n Explore important network details such as what connections were open during tha attack. \n Explore how the attack was initiated. \n \n 4.)Report the attack to higher authorities.'